version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: devcontainer.env
    restart: unless-stopped
    volumes:
      - ..:/home/TFG-Flow:cached
    depends_on:
      - postgres
    network_mode: service:postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - tfg-flow-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tfgflow

volumes:
  tfg-flow-postgres:
